- name: Create database
  become: true
  community.mysql.mysql_db:
    name: "{{ mysql_db }}"
    state: present
    login_user: root
    login_unix_socket: /var/run/mysqld/mysqld.sock
  tags:
    - init_mysql

- name: Add mysql user for database
  become: true
  community.mysql.mysql_user:
    login_user: root
    login_unix_socket: /var/run/mysqld/mysqld.sock
    append_privs: true
    name: "{{ mysql_user }}"
    password: "{{ mysql_pass }}"
    host: '%'
    priv: "{{ mysql_db }}.*:ALL"
    state: present
  tags:
    - init_mysql
